name: build

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        goVersion: [ '1.18.x', '1.19.x' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goVersion }}
      - run: go mod vendor
      - run: make test
      - uses: codecov/codecov-action@v1
        if: always()